language: php

php:
  - '7.4'

notifications:
  email:
  - team@appwrite.io
  
services:
- docker

install:
- docker-compose up -d
- sleep 90

script:
- docker ps
- docker exec appwrite /bin/bash -c '/usr/share/nginx/html/vendor/bin/phpunit'
